version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/instrumentsfinder1
    owner: ubuntu
file_exists_behavior: OVERWRITE
hooks:
    AfterInstall:
        - location: deployscripts/afterinstall.sh

